### ISSUE TITLE
Categories are empty

### ISSUE THREAD

**Issue by davidbe** [add-ons/plugin.video.vrt.nu#1061] opened 2022-10-09 17:38 UTC
### Describe the bug ###
When entering one of the categories in the menu, the result is always the same: an empty list.

### To Reproduce ###
1. Go to Categories
2. Go to _any category_, e.g. Series
3. I see only "..."

### Additional context ###

- Operating system: LibreELEC 9.2.8 on RPi 
- Kodi version: Kodi 18.9
- Addon version: latest: 2.5.18
- Using a VPN: no
- Country you are using the addon from: Belgium

Live tv is possible.
I cleared the cache before running a test with the logs below.

What can I do the investigate this more?

### Log  ###
Log files are not that clear. There is no ERROR message in log.

```
2022-10-09 19:21:34.178 T:1519162240  NOTICE: [plugin.video.vrt.nu] URL get: https://www.vrt.be/vrtmax/categorieen/jcr:content/par/categories.model.json
2022-10-09 19:21:34.570 T:1519162240  NOTICE: [plugin.video.vrt.nu] Write cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/categories.json'.
2022-10-09 19:21:45.261 T:1519162240  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/categories/docu
2022-10-09 19:21:45.265 T:1519162240  NOTICE: [plugin.video.vrt.nu] Got item from cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/favorites.json'
2022-10-09 19:21:45.268 T:1519162240  NOTICE: [plugin.video.vrt.nu] Cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/favorites.json' has not changed, updating mtime only.
2022-10-09 19:21:45.297 T:1519162240  NOTICE: [plugin.video.vrt.nu] Got item from cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/resume_points.json'
2022-10-09 19:21:45.300 T:1519162240  NOTICE: [plugin.video.vrt.nu] Got item from cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/continue.json'
2022-10-09 19:21:45.302 T:1519162240  NOTICE: [plugin.video.vrt.nu] Write cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/cache/continue.json'.
2022-10-09 19:21:45.308 T:1519162240  NOTICE: [plugin.video.vrt.nu] Got item from cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtnusite_profile_at.tkn'
2022-10-09 19:21:45.311 T:1519162240  NOTICE: [plugin.video.vrt.nu] URL post: https://www.vrt.be/vrtnu-api/graphql/v1
2022-10-09 19:21:45.312 T:1519162240  NOTICE: [plugin.video.vrt.nu] URL post data: {"query": "\n            query PaginatedPrograms(\n              $listId: ID!\n              $endCursor: ID!\n              $pageSize: Int!\n            ) {\n              list(listId: $listId) {\n                __typename\n                ... on PaginatedTileList {\n                  paginated: paginatedItems(first: $pageSize, after: $endCursor) {\n                    edges {\n                      node {\n                        __typename\n                        ...ep\n                      }\n                    }\n                    pageInfo {\n                      startCursor\n                      endCursor\n                      hasNextPage\n                      hasPreviousPage\n                      __typename\n                    }\n                  }\n                }\n              }\n            }\n            fragment ep on ProgramTile {\n              __typename\n              objectId\n              id\n              link\n              tileType\n              image {\n                alt\n                templateUrl\n              }\n              title\n              program {\n                title\n                id\n                link\n                programType\n                description\n                shortDescription\n                subtitle\n                announcementType\n                announcementValue\n                whatsonId\n                image {\n                  alt\n                  templateUrl\n                }\n                posterImage {\n                  alt\n                  templateUrl\n                }\n              }\n            }\n        ", "variables": {"listId": "uisearch:searchdata@eyJyZXN1bHRUeXBlIjogIndhdGNoIiwgImZhY2V0cyI6IFt7InZhbHVlcyI6IFsiZG9jdSJdLCAibmFtZSI6ICJjYXRlZ29yaWVzIn1dLCAicXVlcnlTdHJpbmciOiBudWxsfQ==", "endCursor": "", "pageSize": 50}, "operationName": "PaginatedPrograms"}
```

**Comment by mediaminister** [comment] 2022-10-09 19:05
I can't reproduce this problem. I installed LibreELEC 9.2.6 in a virtual machine, but everything works.

Maybe you can provide a full debug log:
- Enable debug logging in Kodi
- Enable debug logging in the VRT MAX add-on Expert settings
More info: [LibreELEC 9.2.8](https://kodi.wiki/view/Log_file/Easy)

**Comment by davidbe** [comment] 2022-10-09 20:02
I had other SBC lying around and just put Kodi on it and it finds entries without issues. I guess maybe image got a bit crazy.

I'm sorry bothering you with it.

**Comment by blowk** [comment] 2022-10-15 09:10
From yesterday the categories are empty again.
Maybe VRT changed the endpoints again?

**Comment by mediaminister** [comment] 2022-10-15 09:36
Yes, VRT changed the categories variable: fixed in https://github.com/add-ons/plugin.video.vrt.nu/commit/56a1c5beaa4c4727852ba9fdee3d75e068333018
Test packages:
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.18+matrix.1-master-bcb4382.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9791709/plugin.video.vrt.nu-2.5.18%2Bmatrix.1-master-bcb4382.zip)
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.18-master-bcb4382.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9791708/plugin.video.vrt.nu-2.5.18-master-bcb4382.zip)

**Comment by blowk** [comment] 2022-10-15 10:09
@mediaminister : Thanks for the quick fix. The categories are working again.

The channels are also broken and only shows the live feed link.
Maybe the changed the endpoint from this as well?

**Comment by mediaminister** [comment] 2022-10-15 16:31
I fixed the channels menu.
Test packages:
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.18+matrix.1-master-cdba144.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9792608/plugin.video.vrt.nu-2.5.18%2Bmatrix.1-master-cdba144.zip)
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.18-master-cdba144.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9792607/plugin.video.vrt.nu-2.5.18-master-cdba144.zip)

**Closed** 2022-10-16 05:26 UTC
Labels: bug
