### ISSUE TITLE
Episode does not play and throws error in log

### ISSUE THREAD

**Issue by TASSDevon** [add-ons/plugin.video.vrt.nu#881] opened 2021-04-22 07:49 UTC
### Describe the bug ###

Episode does not start and errors are printed in the log

### To Reproduce ###
Try to play any episode (I usually play Het Journaal)

### Expected behavior ###
Episodes played fine until this morning

### Additional context ###

- Operating system:
- Kodi version: OSMC with Kodi 18.9
- Addon version: 2.5.1 (checked in Kodi for update but that was the latest it seems)
- Using a VPN: no
- Country you are using the addon from: ...

### Log (if available) ###
```
2021-04-22 06:52:07.304 T:1915564976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/het-journaal-met-vgt) failed
2021-04-22 06:52:22.736 T:1161801952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 360, in run
                                                plugin.run(argv)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 164, in programs
                                                VRTPlayer().show_episodes_menu(program=program, season=season)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 276, in show_episodes_menu
                                                episode_items, sort, ascending, content = self._apihelper.list_episodes(program=program, season=season)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 137, in list_episodes
                                                return self.__map_episodes(episodes, titletype=titletype, season=season, use_favorites=use_favorites, cache_file=cache_file)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 164, in __map_episodes
                                                list_item, sort, ascending = self.episode_to_listitem(episode, program, cache_file, titletype)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 253, in episode_to_listitem
                                                info_labels = self._metadata.get_info_labels(episode)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/metadata.py", line 650, in get_info_labels
                                                plotoutline=self.get_plotoutline(api_data, season=season),
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/metadata.py", line 384, in get_plotoutline
                                                plotoutline = html_to_kodi(api_data.get('subtitle'))
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/utils.py", line 61, in html_to_kodi
                                                text = key.sub(val, text)
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--
2021-04-22 06:52:22.977 T:1170194656   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/het-journaal
2021-04-22 06:52:22.978 T:1915564976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/het-journaal) failed
2021-04-22 06:52:28.638 T:1915564976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/) failed

```

**Comment by mediaminister** [comment] 2021-04-22 09:34
This is a duplicate of https://github.com/add-ons/plugin.video.vrt.nu/issues/879 and was fixed in https://github.com/add-ons/plugin.video.vrt.nu/pull/876
The new v2.5.2 release is already submitted to the official Kodi repository and the VRT NU add-on will be automatically updated in the coming days.

You can install this release manually using a zip package you can download at https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.2

**Closed** 2021-04-24 13:19 UTC
Labels: bug, duplicate
