### ISSUE TITLE
Fetching menu fails on my setup

### ISSUE THREAD

**Issue by JeanPoll** [add-ons/plugin.video.vrt.nu#766] opened 2020-05-27 19:10 UTC
2020-05-27 21:01:48.066 T:1793061600   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.weathericons.default/.png
2020-05-27 21:01:48.119 T:1793061600   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.weathericons.default/
2020-05-27 21:01:48.154 T:1761600224   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.weathericons.default//
2020-05-27 21:02:37.640 T:1512714976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'value'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 336, in run
                                                plugin.run(argv)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 166, in programs
                                                VRTPlayer().show_tvshow_menu()
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 198, in show_tvshow_menu
                                                self._favorites.refresh(ttl=ttl('direct' if use_favorites else 'indirect'))
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 41, in refresh
                                                xvrttoken = TokenResolver().get_xvrttoken(token_variant='user')
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 81, in get_xvrttoken
                                                return self._get_new_user_xvrttoken()
                                              File "/home/osmc/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 234, in _get_new_user_xvrttoken
                                                xsrf = next((cookie for cookie in cookiejar if cookie.name == 'XSRF-TOKEN'), None).value
                                            AttributeError: 'NoneType' object has no attribute 'value'
                                            -->End of Python script error report<--
2020-05-27 21:02:37.794 T:1761600224   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs
2020-05-27 21:02:37.795 T:1915782704   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs) failed

**Comment by dagwieers** [comment] 2020-05-27 19:12
This is a duplicate of #765 and is already fixed. Update to v2.3.5...

**Closed by dagwieers** 2020-05-27 19:12 UTC
Labels: duplicate
