### ISSUE TITLE
Nothing works 

### ISSUE THREAD

**Issue by Rvhalewyn** [add-ons/plugin.video.vrt.nu#916] opened 2021-11-12 21:55 UTC
### Describe the bug ###

Nothing plays, live or VOD

### To Reproduce ###
1. Go to .epg grid 
2. Click on any VRT program 
3. Title visible in upper right-hand corner 
4. Program doesn't start

All other programs do play, only VRT doesn't. 

### Expected behavior ###

Program starting.. '

### Additional context ###

- Operating system: Nvidia Pro 
- Kodi version: 18.3
- Addon version: 2.5. 5+matrix.1
- Using a VPN: no
- Country you are using the addon from: Belgium 

### Log (if available) ###
```paste below


```

**Comment by mediaminister** [comment] 2021-11-13 15:38
I can't reproduce this problem, please provide a log.

**Comment by Rvhalewyn** [comment] 2021-11-13 15:39
Sorry, turned out to be a temporary problem.

**Comment by mediaminister** [comment] 2021-11-13 15:41
Okay. I'll close this.

**Closed by mediaminister** 2021-11-13 15:41 UTC
Labels: invalid
