### ISSUE TITLE
Radio plus support

### ISSUE THREAD

**Issue by JeanPoll** [add-ons/plugin.video.vrt.nu#859] opened 2021-02-19 21:58 UTC
It would be nice to have a radio plus plugin/addon like vrt nu iso of only live radio stream.

**Comment by michaelarnauts** [comment] 2021-02-20 07:37
You'll need to install the VRT Radio Add-on for that.

See https://kodi.wiki/view/Add-on:VRT_Radio

**Comment by dagwieers** [comment] 2021-02-20 08:18
Duplicate of https://github.com/add-ons/plugin.audio.vrt.radio/issues/15

**Closed by dagwieers** 2021-02-20 08:18 UTC
Labels: duplicate, question
