### ISSUE TITLE
Problem to watch FC De Kampioenen

### ISSUE THREAD

**Issue by david63236** [add-ons/plugin.video.vrt.nu#990] opened 2022-05-25 14:36 UTC
Everything seems OK, except for FC De Kampioenen,
it's not possible to watch this serie (from categories/series, from favorites, from TV guide, ...),
== logfile :
2022-05-25 16:31:24.325 T:3252   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vrt.nu/programs/f-c--de-kampioenen
2022-05-25 16:31:24.335 T:8116   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/programs/f-c--de-kampioenen) failed
==  tests : Leia on Android TV, Leia on Windows, Matrix on Windows

**Comment by mediaminister** [comment] 2022-05-25 15:57
This is most likely a duplicate of https://github.com/add-ons/plugin.video.vrt.nu/issues/988

**Closed** 2022-05-25 17:28 UTC
Labels: duplicate
