### ISSUE TITLE
Bad Request when calling programs on TV Guide

### ISSUE THREAD

**Issue by blowk** [add-ons/plugin.video.vrt.nu#958] opened 2022-04-28 17:55 UTC
### To Reproduce ###
1. Go to Één, then TV Gids
2. Click on a program to watch
3. See error HTTP Error 400, Https://search7.vrt.be/search?I=video&site=1&facets[whatsonId]=
Bad Request

### Expected behavior ###

See the clicked program

### Additional context ###

- Operating system: Android TV
- Kodi version: matrix
- Addon version: 2.5.9
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```paste below


```

**Comment by mediaminister** [comment] 2022-04-29 04:11
Duplicate of https://github.com/add-ons/plugin.video.vrt.nu/issues/954
Fixed in https://github.com/add-ons/plugin.video.vrt.nu/pull/956
Fix will be available in add-on version 2.5.10

**Closed** 2022-04-29 04:28 UTC
Labels: duplicate
