### ISSUE TITLE
VRT Max doesn't work anymore (at least vrtr nws)

### ISSUE THREAD

**Issue by peno64** [add-ons/plugin.video.vrt.nu#1117] opened 2023-07-12 19:59 UTC
### Describe the bug ###

Playing vrt nws doesn't work anymore

### To Reproduce ###
1. Categories
2. News and current affairs
3. VRT NWS journaal
4. => VRT MAX error

### Expected behavior ###
You should get a list of all journals

### Additional context ###

- Operating system: LibreElec
- Kodi version: 20.1
- Addon version: 2.5.22+matrix.1
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```paste below

https://hastebin.com/share/hucotomovo.yaml

```

**Comment by abanink** [comment] 2023-07-13 08:00
Probably solved in [this commit](https://github.com/add-ons/plugin.video.vrt.nu/pull/1112/commits/5008e3bab8fc0241f5f4120c0e1ac7e121450c1a).
Update 'vrtmax' to 'vrtnu' in the URL & restart kodi; worked for me.
```

~/.kodi/addons/plugin.video.vrt.nu$ grep vrtnu resources/lib/api.py  |grep season_json
    season_json = get_url_json('https://www.vrt.be/vrtnu/a-z/{}.model.json'.format(program_name))
```

**Comment by peno64** [comment] 2023-07-13 09:33
Indeed, installing the latest master branch solves this issue.

**Comment by doglover3920** [comment] 2023-07-13 11:43
Worked as a charm.
Also change this line:

featured_json = get_url_json('https://www.vrt.be/vrtnu/kijk.model.json')
(line 1042)

**Comment by mediaminister** [comment] 2023-07-15 08:40
Duplicate of https://github.com/add-ons/plugin.video.vrt.nu/issues/1111
Fixed and released: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.23

**Closed by mediaminister** 2023-07-15 08:40 UTC
Labels: duplicate
