### ISSUE TITLE
Kodi 21 no TV-Guide; VRT-Max error reported

### ISSUE THREAD

**Issue by alfaajx732** [add-ons/plugin.video.vrt.nu#1157] opened 2024-04-14 11:45 UTC
### Expected behavior ###
Cannot open the TV-Guide in Kodi 21
VRT-Max error reported

### Additional context ###
Windows 11 and Android
Kodi 21
VRT MAX addon 2.5.29 + Matrix1
No vpn
Belgium

### Log (if available) ###
[kodi - kopie.log](https://github.com/add-ons/plugin.video.vrt.nu/files/14970545/kodi.-.kopie.log)

**Comment by roelschroeven** [comment] 2024-04-15 10:44
Looks like a duplicate of #1158

**Comment by alfaajx732** [comment] 2024-04-15 11:07
> Looks like a duplicate of #1158
Yes but with the difference that Tv-Guide worked fine for me in Kodi 20.5
Error with Kodi 21  In windows 11 and Android 
#1158 mentions Kodi 19.5

**Comment by ErwinBaeyens** [comment] 2024-04-15 18:16
I'm the author of #1158 and I also do think this and #1158 are duplicates.  I did not see that this issue was here when I registerde mine. It is possible that we registered them both at the same time.  I do not think it is an issue with Kodi but with the vrtmax add-on  and so it would be an issue with the 2.5.29 version.

**Comment by mediaminister** [comment] 2024-04-15 20:29
I made a quick fix, please test:

Kodi 19, 20, 21: [plugin.video.vrt.nu-2.5.29+matrix.1-master-87f5e66.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/14984049/plugin.video.vrt.nu-2.5.29%2Bmatrix.1-master-87f5e66.zip)
Kodi 18: [plugin.video.vrt.nu-2.5.29-master-87f5e66.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/14984048/plugin.video.vrt.nu-2.5.29-master-87f5e66.zip)

**Comment by alfaajx732** [comment] 2024-04-16 06:42
> Kodi 19, 20, 21: [plugin.video.vrt.nu-2.5.29+matrix.1-master-87f5e66.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/14984049/plugin.video.vrt.nu-2.5.29%2Bmatrix.1-master-87f5e66.zip)

Tested on W11, TV-guide works fine again, no TV-Max error anymore
Thanks mediaminister

**Comment by blowk** [comment] 2024-04-16 07:00
> I made a quick fix, please test:
> 
> Kodi 19, 20, 21: [plugin.video.vrt.nu-2.5.29+matrix.1-master-87f5e66.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/14984049/plugin.video.vrt.nu-2.5.29%2Bmatrix.1-master-87f5e66.zip) Kodi 18: [plugin.video.vrt.nu-2.5.29-master-87f5e66.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/14984048/plugin.video.vrt.nu-2.5.29-master-87f5e66.zip)

Tested on Android TV, Kodi 21 and TV guide is also working again.
I only have a visual problem. It's showing 'Today: **-d** april 2024'.
I don't know if it's a Kodi problem to change the **-d** to a number.

**Comment by mediaminister** [comment] 2024-04-16 11:02
I get the same "-d problem" with Kodi 21 on Android, but the date formatting was totally fine on Kodi 20.5
I'll look for a solution.

**Comment by alfaajx732** [comment] 2024-04-16 13:20
> I get the same "-d problem" with Kodi 21 on Android, but the date formatting was totally fine on Kodi 20.5

No "-d" problem on windows 11 and kodi 21
And indeed it occurs on Android

**Comment by mediaminister** [comment] 2024-04-16 15:29
I released this fix: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.30
And I reporterd the "-d" problem at https://github.com/xbmc/xbmc/issues

**Closed** 2024-04-16 15:30 UTC
Labels: bug
