### ISSUE TITLE
Getting error "Problem connecting to the Internet"

### ISSUE THREAD

**Issue by TScheen** [add-ons/plugin.video.vrt.nu#907] opened 2021-09-10 07:01 UTC
### Describe the bug ###
Since two days, only live stream still works. When clicking on any VOD, an error message pops up:
”There is a problem connecting with the Internet. This might be due to ISP, ..."
Obviously I’m connected to the Internet.
I’m also using Retrospect as backup for VrtNu and there, everything is fine.
Re-entering VrtNu credentials in settings does not help
Re-install VrtNu add-on (without uninstall) does not help.

### Additional context ###

- Operating system: Phillips Android TV with Android 8
- Kodi version: 19.1
- Addon version: 2.5.4+
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by KarelVOoteghem** [comment] 2021-09-10 08:14
I confirm that I have the same issue with this version of the plugin. Exactly the same context as @TScheen except that I'm running Kodi 18.9 on a Raspberry Pi 3B+.

**Comment by tebokial** [comment] 2021-09-10 08:49
Same problem over here, running Kodi 18.9 on a Raspberry 3B via LibreElec : clicking on "Recent" generates the message "error connecting to the internet ... blabla".    I am attaching the Kodi log (as generated with LibreElec's utitlity)
[3yri_10sep2021.log](https://github.com/add-ons/plugin.video.vrt.nu/files/7142485/3yri_10sep2021.log)

**Comment by mediaminister** [comment] 2021-09-10 09:31
This is a duplicate of https://github.com/add-ons/plugin.video.vrt.nu/issues/906 and this is fixed in https://github.com/add-ons/plugin.video.vrt.nu/pull/902

Please [upgrade to version v2.5.5](https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.5) manually or get the update through the official Kodi repo.

**Comment by TScheen** [comment] 2021-09-10 10:00
Version 2.5.5+ not yet available on Kodi repository. I’ll wait😉

**Comment by krlvo** [comment] 2021-09-10 17:54
Manually installed the update (not available in the official Kodi repo for me yet) and can confirm that this solves the issue. Thanks for the great work!

**Comment by wimvanhoeck** [comment] 2021-09-10 19:05
Manually installed the update and the initial problem is gone.
The internet connectivity error is no longer there and I can select series/shows and view their description.
However, I cannot view any programs because everything is geo-locked.
I am in France and I was watching shows every day before the internet connectivity error appeared.
Using the same VRT account I am able to watch the geo-locked shows on my laptop.
Is it possible that this v2.5.5 does not work outside Belgium?
Thanks!

**Comment by mediaminister** [comment] 2021-09-10 20:50
Very unlikely. Try to clear VRT Tokens in the VRT Nu Add-on Expert settings.
If the problems persists, please provide a debug log: https://kodi.wiki/view/Log_file/Easy

**Comment by wimvanhoeck** [comment] 2021-09-11 08:09
Clearing the tokens did not work. I will provide a log file later today. Thank you.

**Comment by wimvanhoeck** [comment] 2021-09-11 13:12
Problem solved. Turns out that while trying to solve the issue, I played with some settings on Inputstream Adaptive. I have to turn off IA on my 4G internet connection and it was turned on after installing 2.5.5.
Sorry about that and thanks again for the quick fix!

**Closed** 2021-09-11 13:30 UTC
Labels: bug, duplicate
